await page.locator('input[name="username"]').click();
await page.locator('input[name="username"]').fill('Shiveris');
await page.locator('input[name="username"]').press('Tab');
await page.locator('input[name="password"]').fill('shiveris');
await page.locator('input[name="password"]').press('Enter');
await page.getByRole('button', { name: 'Login' }).click();
await page.getByRole('link').nth(2).click();
await page.getByRole('link').nth(2).click();
await page.getByRole('link', { name: ' Nests' }).click();
await page.getByText('SERVICE MANAGEMENT').click();
await page.getByRole('link', { name: ' Users' }).click();
await page.getByRole('link', { name: ' Nodes' }).click();
await page.getByRole('link', { name: ' Databases' }).click();
await page.getByText('MANAGEMENT', { exact: true }).click();
await page.getByRole('link', { name: ' Settings' }).click();
await page.getByRole('button', { name: ' Toggle navigation' }).click();
await page.getByRole('button', { name: ' Toggle navigation' }).click();
await page.getByRole('link', { name: 'User Image Shiveris Shiveris' }).click();
await page.getByRole('link').nth(1).click();
await page.locator('.navigation-link').click();
await page.locator('.navigation-link').click();
await page.locator('#modal-portal').getByRole('img').click();
await page.getByRole('link').nth(2).click();
await page.getByRole('link', { name: ' Databases' }).click();
await page.getByRole('link', { name: ' Locations' }).click();
await page.getByRole('link', { name: ' Nodes' }).click();
await page.getByRole('button', { name: 'Create New' }).click();
await page.getByRole('link', { name: ' Overview' }).click();
await page.getByRole('link', { name: ' Overview' }).click();